package sumeragi

import "time"

var eras = []Era{
	{
		Kanji:    "",
		Hiragana: "",
		Epoch:    time.Date(-660, 1, 1, 0, 0, 0, 0, JST),
		Emperors: []string{"神武天皇", "綏靖天皇", "安寧天皇", "懿徳天皇", "孝昭天皇", "孝安天皇", "孝霊天皇", "孝元天皇", "開化天皇", "崇神天皇", "垂仁天皇", "景行天皇", "成務天皇", "仲哀天皇", "応神天皇", "仁徳天皇", "履中天皇", "反正天皇", "允恭天皇", "安康天皇", "雄略天皇", "清寧天皇", "顕宗天皇", "仁賢天皇", "武烈天皇", "継体天皇", "安閑天皇", "宣化天皇", "欽明天皇", "敏達天皇", "用明天皇", "崇峻天皇", "推古天皇", "舒明天皇", "皇極天皇"},
	},
	{
		Kanji:    "大化",
		Hiragana: "たいか",
		Epoch:    time.Date(645, 7, 17, 0, 0, 0, 0, JST),
		Emperors: []string{"孝徳天皇"},
	},
	{
		Kanji:    "白雉",
		Hiragana: "はくち",
		Epoch:    time.Date(650, 3, 22, 0, 0, 0, 0, JST),
		Emperors: []string{"孝徳天皇"},
	},
	{
		Kanji:    "",
		Hiragana: "",
		Epoch:    time.Date(654, 11, 24, 0, 0, 0, 0, JST),
		Emperors: []string{"斉明天皇", "天智天皇", "弘文天皇"},
	},
	{
		Kanji:    "朱鳥",
		Hiragana: "しゅちょう",
		Epoch:    time.Date(686, 8, 14, 0, 0, 0, 0, JST),
		Emperors: []string{"天武天皇"},
	},
	{
		Kanji:    "",
		Hiragana: "",
		Epoch:    time.Date(687, 2, 18, 0, 0, 0, 0, JST),
		Emperors: []string{"持統天皇", "文武天皇"},
	},
	{
		Kanji:    "大宝",
		Hiragana: "たいほう",
		Epoch:    time.Date(701, 5, 3, 0, 0, 0, 0, JST),
		Emperors: []string{"文武天皇"},
	},
	{
		Kanji:    "慶雲",
		Hiragana: "けいうん",
		Epoch:    time.Date(704, 6, 16, 0, 0, 0, 0, JST),
		Emperors: []string{"文武天皇", "元明天皇"},
	},
	{
		Kanji:    "和銅",
		Hiragana: "わどう",
		Epoch:    time.Date(708, 2, 7, 0, 0, 0, 0, JST),
		Emperors: []string{"元明天皇"},
	},
	{
		Kanji:    "霊亀",
		Hiragana: "れいき",
		Epoch:    time.Date(715, 10, 3, 0, 0, 0, 0, JST),
		Emperors: []string{"元正天皇"},
	},
	{
		Kanji:    "養老",
		Hiragana: "ようろう",
		Epoch:    time.Date(717, 12, 24, 0, 0, 0, 0, JST),
		Emperors: []string{"元正天皇"},
	},
	{
		Kanji:    "神亀",
		Hiragana: "じんき",
		Epoch:    time.Date(724, 3, 3, 0, 0, 0, 0, JST),
		Emperors: []string{"聖武天皇"},
	},
	{
		Kanji:    "天平",
		Hiragana: "てんぴょう",
		Epoch:    time.Date(729, 9, 2, 0, 0, 0, 0, JST),
		Emperors: []string{"聖武天皇"},
	},
	{
		Kanji:    "天平感宝",
		Hiragana: "てんぴょうかんぽう",
		Epoch:    time.Date(749, 5, 4, 0, 0, 0, 0, JST),
		Emperors: []string{"聖武天皇"},
	},
	{
		Kanji:    "天平勝宝",
		Hiragana: "てんぴょうしょうほう",
		Epoch:    time.Date(749, 8, 19, 0, 0, 0, 0, JST),
		Emperors: []string{"孝謙天皇"},
	},
	{
		Kanji:    "天平宝字",
		Hiragana: "てんぴょうほうじ",
		Epoch:    time.Date(757, 9, 6, 0, 0, 0, 0, JST),
		Emperors: []string{"淳仁天皇", "称徳天皇"},
	},
	{
		Kanji:    "天平神護",
		Hiragana: "てんぴょうじんご",
		Epoch:    time.Date(765, 2, 1, 0, 0, 0, 0, JST),
		Emperors: []string{"称徳天皇"},
	},
	{
		Kanji:    "神護景雲",
		Hiragana: "じんごけいうん",
		Epoch:    time.Date(767, 9, 13, 0, 0, 0, 0, JST),
		Emperors: []string{"称徳天皇"},
	},
	{
		Kanji:    "宝亀",
		Hiragana: "ほうき",
		Epoch:    time.Date(770, 10, 23, 0, 0, 0, 0, JST),
		Emperors: []string{"光仁天皇"},
	},
	{
		Kanji:    "天応",
		Hiragana: "てんおう",
		Epoch:    time.Date(781, 1, 30, 0, 0, 0, 0, JST),
		Emperors: []string{"光仁天皇", "桓武天皇"},
	},
	{
		Kanji:    "延暦",
		Hiragana: "えんりゃく",
		Epoch:    time.Date(782, 9, 30, 0, 0, 0, 0, JST),
		Emperors: []string{"桓武天皇"},
	},
	{
		Kanji:    "大同",
		Hiragana: "だいどう",
		Epoch:    time.Date(806, 6, 8, 0, 0, 0, 0, JST),
		Emperors: []string{"平城天皇", "嵯峨天皇"},
	},
	{
		Kanji:    "弘仁",
		Hiragana: "こうにん",
		Epoch:    time.Date(810, 10, 20, 0, 0, 0, 0, JST),
		Emperors: []string{"嵯峨天皇", "淳和天皇"},
	},
	{
		Kanji:    "天長",
		Hiragana: "てんちょう",
		Epoch:    time.Date(824, 2, 8, 0, 0, 0, 0, JST),
		Emperors: []string{"仁明天皇"},
	},
	{
		Kanji:    "承和",
		Hiragana: "じょうわ",
		Epoch:    time.Date(834, 2, 14, 0, 0, 0, 0, JST),
		Emperors: []string{"仁明天皇"},
	},
	{
		Kanji:    "嘉祥",
		Hiragana: "かしょう",
		Epoch:    time.Date(848, 7, 16, 0, 0, 0, 0, JST),
		Emperors: []string{"仁明天皇", "文徳天皇"},
	},
	{
		Kanji:    "仁寿",
		Hiragana: "にんじゅ",
		Epoch:    time.Date(851, 6, 1, 0, 0, 0, 0, JST),
		Emperors: []string{"文徳天皇"},
	},
	{
		Kanji:    "斉衡",
		Hiragana: "さいこう",
		Epoch:    time.Date(854, 12, 23, 0, 0, 0, 0, JST),
		Emperors: []string{"文徳天皇"},
	},
	{
		Kanji:    "天安",
		Hiragana: "てんあん",
		Epoch:    time.Date(857, 3, 20, 0, 0, 0, 0, JST),
		Emperors: []string{"文徳天皇", "清和天皇"},
	},
	{
		Kanji:    "貞観",
		Hiragana: "じょうがん",
		Epoch:    time.Date(859, 5, 20, 0, 0, 0, 0, JST),
		Emperors: []string{"陽成天皇"},
	},
	{
		Kanji:    "元慶",
		Hiragana: "がんぎょう",
		Epoch:    time.Date(877, 6, 1, 0, 0, 0, 0, JST),
		Emperors: []string{"光孝天皇"},
	},
	{
		Kanji:    "仁和",
		Hiragana: "にんな,にんわ",
		Epoch:    time.Date(885, 3, 11, 0, 0, 0, 0, JST),
		Emperors: []string{"光孝天皇", "宇多天皇"},
	},
	{
		Kanji:    "寛平",
		Hiragana: "かんぴょう,かんぺい,かんへい",
		Epoch:    time.Date(889, 5, 30, 0, 0, 0, 0, JST),
		Emperors: []string{"宇多天皇", "醍醐天皇"},
	},
	{
		Kanji:    "昌泰",
		Hiragana: "しょうたい",
		Epoch:    time.Date(898, 5, 20, 0, 0, 0, 0, JST),
		Emperors: []string{"醍醐天皇"},
	},
	{
		Kanji:    "延喜",
		Hiragana: "えんぎ",
		Epoch:    time.Date(901, 8, 31, 0, 0, 0, 0, JST),
		Emperors: []string{"醍醐天皇"},
	},
	{
		Kanji:    "延長",
		Hiragana: "えんちょう",
		Epoch:    time.Date(923, 5, 29, 0, 0, 0, 0, JST),
		Emperors: []string{"朱雀天皇"},
	},
	{
		Kanji:    "承平",
		Hiragana: "じょうへい,しょうへい",
		Epoch:    time.Date(931, 5, 16, 0, 0, 0, 0, JST),
		Emperors: []string{"朱雀天皇"},
	},
	{
		Kanji:    "天慶",
		Hiragana: "てんぎょう,てんきょう",
		Epoch:    time.Date(938, 6, 22, 0, 0, 0, 0, JST),
		Emperors: []string{"朱雀天皇", "村上天皇"},
	},
	{
		Kanji:    "天暦",
		Hiragana: "てんりゃく",
		Epoch:    time.Date(947, 5, 15, 0, 0, 0, 0, JST),
		Emperors: []string{"村上天皇"},
	},
	{
		Kanji:    "天徳",
		Hiragana: "てんとく",
		Epoch:    time.Date(957, 11, 21, 0, 0, 0, 0, JST),
		Emperors: []string{"村上天皇"},
	},
	{
		Kanji:    "応和",
		Hiragana: "おうわ",
		Epoch:    time.Date(961, 3, 5, 0, 0, 0, 0, JST),
		Emperors: []string{"村上天皇"},
	},
	{
		Kanji:    "康保",
		Hiragana: "こうほう",
		Epoch:    time.Date(964, 8, 19, 0, 0, 0, 0, JST),
		Emperors: []string{"冷泉天皇"},
	},
	{
		Kanji:    "安和",
		Hiragana: "あんな,あんわ",
		Epoch:    time.Date(968, 9, 8, 0, 0, 0, 0, JST),
		Emperors: []string{"冷泉天皇", "円融天皇"},
	},
	{
		Kanji:    "天禄",
		Hiragana: "てんろく",
		Epoch:    time.Date(970, 5, 3, 0, 0, 0, 0, JST),
		Emperors: []string{"円融天皇"},
	},
	{
		Kanji:    "天延",
		Hiragana: "てんえん",
		Epoch:    time.Date(974, 1, 16, 0, 0, 0, 0, JST),
		Emperors: []string{"円融天皇"},
	},
	{
		Kanji:    "貞元",
		Hiragana: "じょうげん",
		Epoch:    time.Date(976, 8, 11, 0, 0, 0, 0, JST),
		Emperors: []string{"円融天皇"},
	},
	{
		Kanji:    "天元",
		Hiragana: "てんげん",
		Epoch:    time.Date(978, 12, 31, 0, 0, 0, 0, JST),
		Emperors: []string{"円融天皇"},
	},
	{
		Kanji:    "永観",
		Hiragana: "えいかん",
		Epoch:    time.Date(983, 5, 29, 0, 0, 0, 0, JST),
		Emperors: []string{"花山天皇"},
	},
	{
		Kanji:    "寛和",
		Hiragana: "かんな,かんわ",
		Epoch:    time.Date(985, 5, 19, 0, 0, 0, 0, JST),
		Emperors: []string{"花山天皇", "一条天皇"},
	},
	{
		Kanji:    "永延",
		Hiragana: "えいえん",
		Epoch:    time.Date(987, 5, 5, 0, 0, 0, 0, JST),
		Emperors: []string{"一条天皇"},
	},
	{
		Kanji:    "永祚",
		Hiragana: "えいそ",
		Epoch:    time.Date(989, 9, 10, 0, 0, 0, 0, JST),
		Emperors: []string{"一条天皇"},
	},
	{
		Kanji:    "正暦",
		Hiragana: "しょうりゃく",
		Epoch:    time.Date(990, 11, 26, 0, 0, 0, 0, JST),
		Emperors: []string{"一条天皇"},
	},
	{
		Kanji:    "長徳",
		Hiragana: "ちょうとく",
		Epoch:    time.Date(995, 3, 25, 0, 0, 0, 0, JST),
		Emperors: []string{"一条天皇"},
	},
	{
		Kanji:    "長保",
		Hiragana: "ちょうほう",
		Epoch:    time.Date(999, 2, 1, 0, 0, 0, 0, JST),
		Emperors: []string{"一条天皇"},
	},
	{
		Kanji:    "寛弘",
		Hiragana: "かんこう",
		Epoch:    time.Date(1004, 8, 8, 0, 0, 0, 0, JST),
		Emperors: []string{"三条天皇"},
	},
	{
		Kanji:    "長和",
		Hiragana: "ちょうわ",
		Epoch:    time.Date(1013, 2, 8, 0, 0, 0, 0, JST),
		Emperors: []string{"後一条天皇"},
	},
	{
		Kanji:    "寛仁",
		Hiragana: "かんにん",
		Epoch:    time.Date(1017, 5, 21, 0, 0, 0, 0, JST),
		Emperors: []string{"後一条天皇"},
	},
	{
		Kanji:    "治安",
		Hiragana: "じあん",
		Epoch:    time.Date(1021, 3, 17, 0, 0, 0, 0, JST),
		Emperors: []string{"後一条天皇"},
	},
	{
		Kanji:    "万寿",
		Hiragana: "まんじゅ",
		Epoch:    time.Date(1024, 8, 19, 0, 0, 0, 0, JST),
		Emperors: []string{"後一条天皇"},
	},
	{
		Kanji:    "長元",
		Hiragana: "ちょうげん",
		Epoch:    time.Date(1028, 8, 18, 0, 0, 0, 0, JST),
		Emperors: []string{"後朱雀天皇"},
	},
	{
		Kanji:    "長暦",
		Hiragana: "ちょうりゃく",
		Epoch:    time.Date(1037, 5, 9, 0, 0, 0, 0, JST),
		Emperors: []string{"後朱雀天皇"},
	},
	{
		Kanji:    "長久",
		Hiragana: "ちょうきゅう",
		Epoch:    time.Date(1040, 12, 16, 0, 0, 0, 0, JST),
		Emperors: []string{"後朱雀天皇"},
	},
	{
		Kanji:    "寛徳",
		Hiragana: "かんとく",
		Epoch:    time.Date(1044, 12, 16, 0, 0, 0, 0, JST),
		Emperors: []string{"後冷泉天皇"},
	},
	{
		Kanji:    "永承",
		Hiragana: "えいしょう,えいじょう",
		Epoch:    time.Date(1046, 5, 22, 0, 0, 0, 0, JST),
		Emperors: []string{"後冷泉天皇"},
	},
	{
		Kanji:    "天喜",
		Hiragana: "てんき,てんぎ",
		Epoch:    time.Date(1053, 2, 2, 0, 0, 0, 0, JST),
		Emperors: []string{"後冷泉天皇"},
	},
	{
		Kanji:    "康平",
		Hiragana: "こうへい",
		Epoch:    time.Date(1058, 9, 19, 0, 0, 0, 0, JST),
		Emperors: []string{"後冷泉天皇"},
	},
	{
		Kanji:    "治暦",
		Hiragana: "じりゃく",
		Epoch:    time.Date(1065, 9, 4, 0, 0, 0, 0, JST),
		Emperors: []string{"後三条天皇"},
	},
	{
		Kanji:    "延久",
		Hiragana: "えんきゅう",
		Epoch:    time.Date(1069, 5, 6, 0, 0, 0, 0, JST),
		Emperors: []string{"白河天皇"},
	},
	{
		Kanji:    "承保",
		Hiragana: "じょうほう,しょうほう",
		Epoch:    time.Date(1074, 9, 16, 0, 0, 0, 0, JST),
		Emperors: []string{"白河天皇"},
	},
	{
		Kanji:    "承暦",
		Hiragana: "じょうりゃく,しょうりゃく",
		Epoch:    time.Date(1077, 12, 5, 0, 0, 0, 0, JST),
		Emperors: []string{"白河天皇"},
	},
	{
		Kanji:    "永保",
		Hiragana: "えいほう",
		Epoch:    time.Date(1081, 3, 22, 0, 0, 0, 0, JST),
		Emperors: []string{"白河天皇"},
	},
	{
		Kanji:    "応徳",
		Hiragana: "おうとく",
		Epoch:    time.Date(1084, 3, 15, 0, 0, 0, 0, JST),
		Emperors: []string{"堀河天皇"},
	},
	{
		Kanji:    "寛治",
		Hiragana: "かんじ",
		Epoch:    time.Date(1087, 5, 11, 0, 0, 0, 0, JST),
		Emperors: []string{"堀河天皇"},
	},
	{
		Kanji:    "嘉保",
		Hiragana: "かほう",
		Epoch:    time.Date(1095, 1, 23, 0, 0, 0, 0, JST),
		Emperors: []string{"堀河天皇"},
	},
	{
		Kanji:    "永長",
		Hiragana: "えいちょう",
		Epoch:    time.Date(1097, 1, 3, 0, 0, 0, 0, JST),
		Emperors: []string{"堀河天皇"},
	},
	{
		Kanji:    "承徳",
		Hiragana: "じょうとく,しょうとく",
		Epoch:    time.Date(1097, 12, 27, 0, 0, 0, 0, JST),
		Emperors: []string{"堀河天皇"},
	},
	{
		Kanji:    "康和",
		Hiragana: "こうわ",
		Epoch:    time.Date(1099, 9, 15, 0, 0, 0, 0, JST),
		Emperors: []string{"堀河天皇"},
	},
	{
		Kanji:    "長治",
		Hiragana: "ちょうじ",
		Epoch:    time.Date(1104, 3, 8, 0, 0, 0, 0, JST),
		Emperors: []string{"堀河天皇"},
	},
	{
		Kanji:    "嘉承",
		Hiragana: "かしょう,かじょう",
		Epoch:    time.Date(1106, 5, 13, 0, 0, 0, 0, JST),
		Emperors: []string{"堀河天皇", "鳥羽天皇"},
	},
	{
		Kanji:    "天仁",
		Hiragana: "てんにん",
		Epoch:    time.Date(1108, 9, 9, 0, 0, 0, 0, JST),
		Emperors: []string{"鳥羽天皇"},
	},
	{
		Kanji:    "天永",
		Hiragana: "てんえい",
		Epoch:    time.Date(1110, 7, 31, 0, 0, 0, 0, JST),
		Emperors: []string{"鳥羽天皇"},
	},
	{
		Kanji:    "永久",
		Hiragana: "えいきゅう",
		Epoch:    time.Date(1113, 8, 25, 0, 0, 0, 0, JST),
		Emperors: []string{"鳥羽天皇"},
	},
	{
		Kanji:    "元永",
		Hiragana: "げんえい",
		Epoch:    time.Date(1118, 4, 25, 0, 0, 0, 0, JST),
		Emperors: []string{"鳥羽天皇"},
	},
	{
		Kanji:    "保安",
		Hiragana: "ほうあん",
		Epoch:    time.Date(1120, 5, 9, 0, 0, 0, 0, JST),
		Emperors: []string{"崇徳天皇"},
	},
	{
		Kanji:    "天治",
		Hiragana: "てんじ",
		Epoch:    time.Date(1124, 5, 18, 0, 0, 0, 0, JST),
		Emperors: []string{"崇徳天皇"},
	},
	{
		Kanji:    "大治",
		Hiragana: "だいじ",
		Epoch:    time.Date(1126, 2, 15, 0, 0, 0, 0, JST),
		Emperors: []string{"崇徳天皇"},
	},
	{
		Kanji:    "天承",
		Hiragana: "てんしょう,てんじょう",
		Epoch:    time.Date(1131, 2, 28, 0, 0, 0, 0, JST),
		Emperors: []string{"崇徳天皇"},
	},
	{
		Kanji:    "長承",
		Hiragana: "ちょうしょう",
		Epoch:    time.Date(1132, 9, 21, 0, 0, 0, 0, JST),
		Emperors: []string{"崇徳天皇"},
	},
	{
		Kanji:    "保延",
		Hiragana: "ほうえん",
		Epoch:    time.Date(1135, 6, 10, 0, 0, 0, 0, JST),
		Emperors: []string{"崇徳天皇"},
	},
	{
		Kanji:    "永治",
		Hiragana: "えいじ",
		Epoch:    time.Date(1141, 8, 13, 0, 0, 0, 0, JST),
		Emperors: []string{"近衛天皇"},
	},
	{
		Kanji:    "康治",
		Hiragana: "こうじ",
		Epoch:    time.Date(1142, 5, 25, 0, 0, 0, 0, JST),
		Emperors: []string{"近衛天皇"},
	},
	{
		Kanji:    "天養",
		Hiragana: "てんよう",
		Epoch:    time.Date(1144, 3, 28, 0, 0, 0, 0, JST),
		Emperors: []string{"近衛天皇"},
	},
	{
		Kanji:    "久安",
		Hiragana: "きゅうあん",
		Epoch:    time.Date(1145, 8, 12, 0, 0, 0, 0, JST),
		Emperors: []string{"近衛天皇"},
	},
	{
		Kanji:    "仁平",
		Hiragana: "にんぺい,にんぴょう",
		Epoch:    time.Date(1151, 2, 14, 0, 0, 0, 0, JST),
		Emperors: []string{"近衛天皇"},
	},
	{
		Kanji:    "久寿",
		Hiragana: "きゅうじゅ",
		Epoch:    time.Date(1154, 12, 4, 0, 0, 0, 0, JST),
		Emperors: []string{"後白河天皇"},
	},
	{
		Kanji:    "保元",
		Hiragana: "ほうげん",
		Epoch:    time.Date(1156, 5, 18, 0, 0, 0, 0, JST),
		Emperors: []string{"二条天皇"},
	},
	{
		Kanji:    "平治",
		Hiragana: "へいじ",
		Epoch:    time.Date(1159, 5, 9, 0, 0, 0, 0, JST),
		Emperors: []string{"二条天皇"},
	},
	{
		Kanji:    "永暦",
		Hiragana: "えいりゃく",
		Epoch:    time.Date(1160, 2, 18, 0, 0, 0, 0, JST),
		Emperors: []string{"二条天皇"},
	},
	{
		Kanji:    "応保",
		Hiragana: "おうほう,おうほ",
		Epoch:    time.Date(1161, 9, 24, 0, 0, 0, 0, JST),
		Emperors: []string{"二条天皇"},
	},
	{
		Kanji:    "長寛",
		Hiragana: "ちょうかん",
		Epoch:    time.Date(1163, 5, 4, 0, 0, 0, 0, JST),
		Emperors: []string{"二条天皇"},
	},
	{
		Kanji:    "永万",
		Hiragana: "えいまん",
		Epoch:    time.Date(1165, 7, 14, 0, 0, 0, 0, JST),
		Emperors: []string{"六条天皇"},
	},
	{
		Kanji:    "仁安",
		Hiragana: "にんあん",
		Epoch:    time.Date(1166, 9, 23, 0, 0, 0, 0, JST),
		Emperors: []string{"高倉天皇"},
	},
	{
		Kanji:    "嘉応",
		Hiragana: "かおう",
		Epoch:    time.Date(1169, 5, 6, 0, 0, 0, 0, JST),
		Emperors: []string{"高倉天皇"},
	},
	{
		Kanji:    "承安",
		Hiragana: "しょうあん",
		Epoch:    time.Date(1171, 5, 27, 0, 0, 0, 0, JST),
		Emperors: []string{"高倉天皇"},
	},
	{
		Kanji:    "安元",
		Hiragana: "あんげん",
		Epoch:    time.Date(1175, 8, 16, 0, 0, 0, 0, JST),
		Emperors: []string{"高倉天皇"},
	},
	{
		Kanji:    "治承",
		Hiragana: "じしょう",
		Epoch:    time.Date(1177, 8, 29, 0, 0, 0, 0, JST),
		Emperors: []string{"安徳天皇"},
	},
	{
		Kanji:    "養和",
		Hiragana: "ようわ",
		Epoch:    time.Date(1181, 8, 25, 0, 0, 0, 0, JST),
		Emperors: []string{"安徳天皇"},
	},
	{
		Kanji:    "寿永",
		Hiragana: "じゅえい",
		Epoch:    time.Date(1182, 6, 29, 0, 0, 0, 0, JST),
		Emperors: []string{"後鳥羽天皇"},
	},
	{
		Kanji:    "元暦",
		Hiragana: "げんりゃく",
		Epoch:    time.Date(1184, 5, 27, 0, 0, 0, 0, JST),
		Emperors: []string{"後鳥羽天皇"},
	},
	{
		Kanji:    "文治",
		Hiragana: "ぶんじ",
		Epoch:    time.Date(1185, 9, 9, 0, 0, 0, 0, JST),
		Emperors: []string{"後鳥羽天皇"},
	},
	{
		Kanji:    "建久",
		Hiragana: "けんきゅう",
		Epoch:    time.Date(1190, 5, 16, 0, 0, 0, 0, JST),
		Emperors: []string{"土御門天皇"},
	},
	{
		Kanji:    "正治",
		Hiragana: "しょうじ",
		Epoch:    time.Date(1199, 5, 23, 0, 0, 0, 0, JST),
		Emperors: []string{"土御門天皇"},
	},
	{
		Kanji:    "建仁",
		Hiragana: "けんにん",
		Epoch:    time.Date(1201, 3, 19, 0, 0, 0, 0, JST),
		Emperors: []string{"土御門天皇"},
	},
	{
		Kanji:    "元久",
		Hiragana: "げんきゅう",
		Epoch:    time.Date(1204, 3, 23, 0, 0, 0, 0, JST),
		Emperors: []string{"土御門天皇"},
	},
	{
		Kanji:    "建永",
		Hiragana: "けんえい",
		Epoch:    time.Date(1206, 6, 5, 0, 0, 0, 0, JST),
		Emperors: []string{"土御門天皇"},
	},
	{
		Kanji:    "承元",
		Hiragana: "じょうげん",
		Epoch:    time.Date(1207, 11, 16, 0, 0, 0, 0, JST),
		Emperors: []string{"順徳天皇"},
	},
	{
		Kanji:    "建暦",
		Hiragana: "けんりゃく",
		Epoch:    time.Date(1211, 4, 23, 0, 0, 0, 0, JST),
		Emperors: []string{"順徳天皇"},
	},
	{
		Kanji:    "建保",
		Hiragana: "けんぽう",
		Epoch:    time.Date(1214, 1, 18, 0, 0, 0, 0, JST),
		Emperors: []string{"順徳天皇"},
	},
	{
		Kanji:    "承久",
		Hiragana: "じょうきゅう",
		Epoch:    time.Date(1219, 5, 27, 0, 0, 0, 0, JST),
		Emperors: []string{"仲恭天皇", "後堀河天皇"},
	},
	{
		Kanji:    "貞応",
		Hiragana: "じょうおう",
		Epoch:    time.Date(1222, 5, 25, 0, 0, 0, 0, JST),
		Emperors: []string{"後堀河天皇"},
	},
	{
		Kanji:    "元仁",
		Hiragana: "げんにん",
		Epoch:    time.Date(1224, 12, 31, 0, 0, 0, 0, JST),
		Emperors: []string{"後堀河天皇"},
	},
	{
		Kanji:    "嘉禄",
		Hiragana: "かろく",
		Epoch:    time.Date(1225, 5, 28, 0, 0, 0, 0, JST),
		Emperors: []string{"後堀河天皇"},
	},
	{
		Kanji:    "安貞",
		Hiragana: "あんてい",
		Epoch:    time.Date(1228, 1, 18, 0, 0, 0, 0, JST),
		Emperors: []string{"後堀河天皇"},
	},
	{
		Kanji:    "寛喜",
		Hiragana: "かんき",
		Epoch:    time.Date(1229, 3, 31, 0, 0, 0, 0, JST),
		Emperors: []string{"後堀河天皇"},
	},
	{
		Kanji:    "貞永",
		Hiragana: "じょうえい",
		Epoch:    time.Date(1232, 4, 23, 0, 0, 0, 0, JST),
		Emperors: []string{"四条天皇"},
	},
	{
		Kanji:    "天福",
		Hiragana: "てんぷく",
		Epoch:    time.Date(1233, 5, 25, 0, 0, 0, 0, JST),
		Emperors: []string{"四条天皇"},
	},
	{
		Kanji:    "文暦",
		Hiragana: "ぶんりゃく",
		Epoch:    time.Date(1234, 11, 27, 0, 0, 0, 0, JST),
		Emperors: []string{"四条天皇"},
	},
	{
		Kanji:    "嘉禎",
		Hiragana: "かてい",
		Epoch:    time.Date(1235, 11, 1, 0, 0, 0, 0, JST),
		Emperors: []string{"四条天皇"},
	},
	{
		Kanji:    "暦仁",
		Hiragana: "りゃくにん",
		Epoch:    time.Date(1238, 12, 30, 0, 0, 0, 0, JST),
		Emperors: []string{"四条天皇"},
	},
	{
		Kanji:    "延応",
		Hiragana: "えんおう",
		Epoch:    time.Date(1239, 3, 13, 0, 0, 0, 0, JST),
		Emperors: []string{"四条天皇"},
	},
	{
		Kanji:    "仁治",
		Hiragana: "にんじ",
		Epoch:    time.Date(1240, 8, 5, 0, 0, 0, 0, JST),
		Emperors: []string{"後嵯峨天皇"},
	},
	{
		Kanji:    "寛元",
		Hiragana: "かんげん",
		Epoch:    time.Date(1243, 3, 18, 0, 0, 0, 0, JST),
		Emperors: []string{"後深草天皇"},
	},
	{
		Kanji:    "宝治",
		Hiragana: "ほうじ",
		Epoch:    time.Date(1247, 4, 5, 0, 0, 0, 0, JST),
		Emperors: []string{"後深草天皇"},
	},
	{
		Kanji:    "建長",
		Hiragana: "けんちょう",
		Epoch:    time.Date(1249, 5, 2, 0, 0, 0, 0, JST),
		Emperors: []string{"後深草天皇"},
	},
	{
		Kanji:    "康元",
		Hiragana: "こうげん",
		Epoch:    time.Date(1256, 10, 24, 0, 0, 0, 0, JST),
		Emperors: []string{"後深草天皇"},
	},
	{
		Kanji:    "正嘉",
		Hiragana: "しょうか",
		Epoch:    time.Date(1257, 3, 31, 0, 0, 0, 0, JST),
		Emperors: []string{"後深草天皇"},
	},
	{
		Kanji:    "正元",
		Hiragana: "しょうげん",
		Epoch:    time.Date(1259, 4, 20, 0, 0, 0, 0, JST),
		Emperors: []string{"亀山天皇"},
	},
	{
		Kanji:    "文応",
		Hiragana: "ぶんおう",
		Epoch:    time.Date(1260, 5, 24, 0, 0, 0, 0, JST),
		Emperors: []string{"亀山天皇"},
	},
	{
		Kanji:    "弘長",
		Hiragana: "こうちょう",
		Epoch:    time.Date(1261, 3, 22, 0, 0, 0, 0, JST),
		Emperors: []string{"亀山天皇"},
	},
	{
		Kanji:    "文永",
		Hiragana: "ぶんえい",
		Epoch:    time.Date(1264, 3, 27, 0, 0, 0, 0, JST),
		Emperors: []string{"後宇多天皇"},
	},
	{
		Kanji:    "建治",
		Hiragana: "けんじ",
		Epoch:    time.Date(1275, 5, 22, 0, 0, 0, 0, JST),
		Emperors: []string{"後宇多天皇"},
	},
	{
		Kanji:    "弘安",
		Hiragana: "こうあん",
		Epoch:    time.Date(1278, 3, 23, 0, 0, 0, 0, JST),
		Emperors: []string{"伏見天皇"},
	},
	{
		Kanji:    "正応",
		Hiragana: "しょうおう",
		Epoch:    time.Date(1288, 5, 29, 0, 0, 0, 0, JST),
		Emperors: []string{"伏見天皇"},
	},
	{
		Kanji:    "永仁",
		Hiragana: "えいにん",
		Epoch:    time.Date(1293, 9, 6, 0, 0, 0, 0, JST),
		Emperors: []string{"後伏見天皇"},
	},
	{
		Kanji:    "正安",
		Hiragana: "しょうあん",
		Epoch:    time.Date(1299, 5, 25, 0, 0, 0, 0, JST),
		Emperors: []string{"後二条天皇"},
	},
	{
		Kanji:    "乾元",
		Hiragana: "けんげん",
		Epoch:    time.Date(1302, 12, 10, 0, 0, 0, 0, JST),
		Emperors: []string{"後二条天皇"},
	},
	{
		Kanji:    "嘉元",
		Hiragana: "かげん",
		Epoch:    time.Date(1303, 9, 16, 0, 0, 0, 0, JST),
		Emperors: []string{"後二条天皇"},
	},
	{
		Kanji:    "徳治",
		Hiragana: "とくじ",
		Epoch:    time.Date(1307, 1, 18, 0, 0, 0, 0, JST),
		Emperors: []string{"花園天皇"},
	},
	{
		Kanji:    "延慶",
		Hiragana: "えんきょう",
		Epoch:    time.Date(1308, 11, 22, 0, 0, 0, 0, JST),
		Emperors: []string{"花園天皇"},
	},
	{
		Kanji:    "応長",
		Hiragana: "おうちょう",
		Epoch:    time.Date(1311, 5, 17, 0, 0, 0, 0, JST),
		Emperors: []string{"花園天皇"},
	},
	{
		Kanji:    "正和",
		Hiragana: "しょうわ",
		Epoch:    time.Date(1312, 4, 27, 0, 0, 0, 0, JST),
		Emperors: []string{"花園天皇"},
	},
	{
		Kanji:    "文保",
		Hiragana: "ぶんぽう",
		Epoch:    time.Date(1317, 3, 16, 0, 0, 0, 0, JST),
		Emperors: []string{"後醍醐天皇"},
	},
	{
		Kanji:    "元応",
		Hiragana: "げんおう",
		Epoch:    time.Date(1319, 5, 18, 0, 0, 0, 0, JST),
		Emperors: []string{"後醍醐天皇"},
	},
	{
		Kanji:    "元亨",
		Hiragana: "げんこう",
		Epoch:    time.Date(1321, 3, 22, 0, 0, 0, 0, JST),
		Emperors: []string{"後醍醐天皇"},
	},
	{
		Kanji:    "正中",
		Hiragana: "しょうちゅう",
		Epoch:    time.Date(1324, 12, 25, 0, 0, 0, 0, JST),
		Emperors: []string{"後醍醐天皇"},
	},
	{
		Kanji:    "嘉暦",
		Hiragana: "かりゃく",
		Epoch:    time.Date(1326, 5, 28, 0, 0, 0, 0, JST),
		Emperors: []string{"後醍醐天皇"},
	},
	{
		Kanji:    "元徳",
		Hiragana: "げんとく",
		Epoch:    time.Date(1329, 9, 22, 0, 0, 0, 0, JST),
		Emperors: []string{"後醍醐天皇"},
	},
	{
		Kanji:    "元弘",
		Hiragana: "げんこう",
		Epoch:    time.Date(1331, 9, 11, 0, 0, 0, 0, JST),
		Emperors: []string{"後醍醐天皇"},
	},
	{
		Kanji:    "正慶",
		Hiragana: "しょうきょう,しょうけい",
		Epoch:    time.Date(1332, 5, 23, 0, 0, 0, 0, JST),
		Emperors: []string{"光厳天皇"},
	},
	{
		Kanji:    "建武",
		Hiragana: "けんむ",
		Epoch:    time.Date(1334, 3, 5, 0, 0, 0, 0, JST),
		Emperors: []string{"後醍醐天皇"},
	},
	{
		Kanji:    "延元",
		Hiragana: "えんげん",
		Epoch:    time.Date(1336, 4, 11, 0, 0, 0, 0, JST),
		Emperors: []string{"後醍醐天皇", "後村上天皇"},
	},
	{
		Kanji:    "暦応",
		Hiragana: "りゃくおう,れきおう",
		Epoch:    time.Date(1338, 10, 11, 0, 0, 0, 0, JST),
		Emperors: []string{"光明天皇"},
	},
	{
		Kanji:    "興国",
		Hiragana: "こうこく",
		Epoch:    time.Date(1340, 5, 25, 0, 0, 0, 0, JST),
		Emperors: []string{"後村上天皇"},
	},
	{
		Kanji:    "康永",
		Hiragana: "こうえい",
		Epoch:    time.Date(1342, 6, 1, 0, 0, 0, 0, JST),
		Emperors: []string{"光明天皇"},
	},
	{
		Kanji:    "貞和",
		Hiragana: "じょうわ,ていわ",
		Epoch:    time.Date(1345, 11, 15, 0, 0, 0, 0, JST),
		Emperors: []string{"光明天皇", "崇光天皇"},
	},
	{
		Kanji:    "正平",
		Hiragana: "しょうへい",
		Epoch:    time.Date(1347, 1, 20, 0, 0, 0, 0, JST),
		Emperors: []string{"長慶天皇"},
	},
	{
		Kanji:    "観応",
		Hiragana: "かんのう,かんおう",
		Epoch:    time.Date(1350, 4, 4, 0, 0, 0, 0, JST),
		Emperors: []string{"崇光天皇"},
	},
	{
		Kanji:    "文和",
		Hiragana: "ぶんな,ぶんわ",
		Epoch:    time.Date(1352, 11, 4, 0, 0, 0, 0, JST),
		Emperors: []string{"後光厳天皇"},
	},
	{
		Kanji:    "延文",
		Hiragana: "えんぶん",
		Epoch:    time.Date(1356, 4, 29, 0, 0, 0, 0, JST),
		Emperors: []string{"後光厳天皇"},
	},
	{
		Kanji:    "康安",
		Hiragana: "こうあん",
		Epoch:    time.Date(1361, 5, 4, 0, 0, 0, 0, JST),
		Emperors: []string{"後光厳天皇"},
	},
	{
		Kanji:    "貞治",
		Hiragana: "じょうじ,ていじ",
		Epoch:    time.Date(1362, 10, 11, 0, 0, 0, 0, JST),
		Emperors: []string{"後光厳天皇"},
	},
	{
		Kanji:    "応安",
		Hiragana: "おうあん",
		Epoch:    time.Date(1368, 3, 7, 0, 0, 0, 0, JST),
		Emperors: []string{"後光厳天皇", "後円融天皇"},
	},
	{
		Kanji:    "建徳",
		Hiragana: "けんとく",
		Epoch:    time.Date(1370, 8, 16, 0, 0, 0, 0, JST),
		Emperors: []string{"長慶天皇"},
	},
	{
		Kanji:    "文中",
		Hiragana: "ぶんちゅう",
		Epoch:    time.Date(1372, 5, 4, 0, 0, 0, 0, JST),
		Emperors: []string{"長慶天皇"},
	},
	{
		Kanji:    "永和",
		Hiragana: "えいわ",
		Epoch:    time.Date(1375, 3, 29, 0, 0, 0, 0, JST),
		Emperors: []string{"後円融天皇"},
	},
	{
		Kanji:    "天授",
		Hiragana: "てんじゅ",
		Epoch:    time.Date(1375, 6, 26, 0, 0, 0, 0, JST),
		Emperors: []string{"長慶天皇"},
	},
	{
		Kanji:    "康暦",
		Hiragana: "こうりゃく",
		Epoch:    time.Date(1379, 4, 9, 0, 0, 0, 0, JST),
		Emperors: []string{"後円融天皇"},
	},
	{
		Kanji:    "弘和",
		Hiragana: "こうわ",
		Epoch:    time.Date(1381, 3, 6, 0, 0, 0, 0, JST),
		Emperors: []string{"後亀山天皇"},
	},
	{
		Kanji:    "永徳",
		Hiragana: "えいとく",
		Epoch:    time.Date(1381, 3, 20, 0, 0, 0, 0, JST),
		Emperors: []string{"後円融天皇", "後小松天皇"},
	},
	{
		Kanji:    "至徳",
		Hiragana: "しとく",
		Epoch:    time.Date(1384, 3, 19, 0, 0, 0, 0, JST),
		Emperors: []string{"後小松天皇"},
	},
	{
		Kanji:    "元中",
		Hiragana: "げんちゅう",
		Epoch:    time.Date(1384, 5, 18, 0, 0, 0, 0, JST),
		Emperors: []string{"後亀山天皇"},
	},
	{
		Kanji:    "嘉慶",
		Hiragana: "かきょう,かけい",
		Epoch:    time.Date(1387, 10, 5, 0, 0, 0, 0, JST),
		Emperors: []string{"後小松天皇"},
	},
	{
		Kanji:    "康応",
		Hiragana: "こうおう",
		Epoch:    time.Date(1389, 3, 7, 0, 0, 0, 0, JST),
		Emperors: []string{"後小松天皇"},
	},
	{
		Kanji:    "明徳",
		Hiragana: "めいとく",
		Epoch:    time.Date(1390, 4, 12, 0, 0, 0, 0, JST),
		Emperors: []string{"後小松天皇"},
	},
	{
		Kanji:    "応永",
		Hiragana: "おうえい",
		Epoch:    time.Date(1394, 8, 2, 0, 0, 0, 0, JST),
		Emperors: []string{"後小松天皇", "称光天皇"},
	},
	{
		Kanji:    "正長",
		Hiragana: "しょうちょう",
		Epoch:    time.Date(1428, 6, 10, 0, 0, 0, 0, JST),
		Emperors: []string{"称光天皇", "後花園天皇"},
	},
	{
		Kanji:    "永享",
		Hiragana: "えいきょう",
		Epoch:    time.Date(1429, 10, 3, 0, 0, 0, 0, JST),
		Emperors: []string{"後花園天皇"},
	},
	{
		Kanji:    "嘉吉",
		Hiragana: "かきつ",
		Epoch:    time.Date(1441, 3, 10, 0, 0, 0, 0, JST),
		Emperors: []string{"後花園天皇"},
	},
	{
		Kanji:    "文安",
		Hiragana: "ぶんあん",
		Epoch:    time.Date(1444, 2, 23, 0, 0, 0, 0, JST),
		Emperors: []string{"後花園天皇"},
	},
	{
		Kanji:    "宝徳",
		Hiragana: "ほうとく",
		Epoch:    time.Date(1449, 8, 16, 0, 0, 0, 0, JST),
		Emperors: []string{"後花園天皇"},
	},
	{
		Kanji:    "享徳",
		Hiragana: "きょうとく",
		Epoch:    time.Date(1452, 8, 10, 0, 0, 0, 0, JST),
		Emperors: []string{"後花園天皇"},
	},
	{
		Kanji:    "康正",
		Hiragana: "こうしょう",
		Epoch:    time.Date(1455, 9, 6, 0, 0, 0, 0, JST),
		Emperors: []string{"後花園天皇"},
	},
	{
		Kanji:    "長禄",
		Hiragana: "ちょうろく",
		Epoch:    time.Date(1457, 10, 16, 0, 0, 0, 0, JST),
		Emperors: []string{"後花園天皇"},
	},
	{
		Kanji:    "寛正",
		Hiragana: "かんしょう",
		Epoch:    time.Date(1461, 2, 1, 0, 0, 0, 0, JST),
		Emperors: []string{"後土御門天皇"},
	},
	{
		Kanji:    "文正",
		Hiragana: "ぶんしょう",
		Epoch:    time.Date(1466, 3, 14, 0, 0, 0, 0, JST),
		Emperors: []string{"後土御門天皇"},
	},
	{
		Kanji:    "応仁",
		Hiragana: "おうにん",
		Epoch:    time.Date(1467, 4, 9, 0, 0, 0, 0, JST),
		Emperors: []string{"後土御門天皇"},
	},
	{
		Kanji:    "文明",
		Hiragana: "ぶんめい",
		Epoch:    time.Date(1469, 6, 8, 0, 0, 0, 0, JST),
		Emperors: []string{"後土御門天皇"},
	},
	{
		Kanji:    "長享",
		Hiragana: "ちょうきょう",
		Epoch:    time.Date(1487, 8, 9, 0, 0, 0, 0, JST),
		Emperors: []string{"後土御門天皇"},
	},
	{
		Kanji:    "延徳",
		Hiragana: "えんとく",
		Epoch:    time.Date(1489, 9, 16, 0, 0, 0, 0, JST),
		Emperors: []string{"後土御門天皇"},
	},
	{
		Kanji:    "明応",
		Hiragana: "めいおう",
		Epoch:    time.Date(1492, 8, 12, 0, 0, 0, 0, JST),
		Emperors: []string{"後柏原天皇"},
	},
	{
		Kanji:    "文亀",
		Hiragana: "ぶんき",
		Epoch:    time.Date(1501, 3, 18, 0, 0, 0, 0, JST),
		Emperors: []string{"後柏原天皇"},
	},
	{
		Kanji:    "永正",
		Hiragana: "えいしょう",
		Epoch:    time.Date(1504, 3, 16, 0, 0, 0, 0, JST),
		Emperors: []string{"後柏原天皇"},
	},
	{
		Kanji:    "大永",
		Hiragana: "だいえい",
		Epoch:    time.Date(1521, 9, 23, 0, 0, 0, 0, JST),
		Emperors: []string{"後奈良天皇"},
	},
	{
		Kanji:    "享禄",
		Hiragana: "きょうろく",
		Epoch:    time.Date(1528, 9, 3, 0, 0, 0, 0, JST),
		Emperors: []string{"後奈良天皇"},
	},
	{
		Kanji:    "天文",
		Hiragana: "てんぶん",
		Epoch:    time.Date(1532, 8, 29, 0, 0, 0, 0, JST),
		Emperors: []string{"後奈良天皇"},
	},
	{
		Kanji:    "弘治",
		Hiragana: "こうじ",
		Epoch:    time.Date(1555, 11, 7, 0, 0, 0, 0, JST),
		Emperors: []string{"正親町天皇"},
	},
	{
		Kanji:    "永禄",
		Hiragana: "えいろく",
		Epoch:    time.Date(1558, 3, 18, 0, 0, 0, 0, JST),
		Emperors: []string{"正親町天皇"},
	},
	{
		Kanji:    "元亀",
		Hiragana: "げんき",
		Epoch:    time.Date(1570, 5, 27, 0, 0, 0, 0, JST),
		Emperors: []string{"正親町天皇"},
	},
	{
		Kanji:    "天正",
		Hiragana: "てんしょう",
		Epoch:    time.Date(1573, 8, 25, 0, 0, 0, 0, JST),
		Emperors: []string{"正親町天皇", "後陽成天皇"},
	},
	{
		Kanji:    "文禄",
		Hiragana: "ぶんろく",
		Epoch:    time.Date(1593, 1, 10, 0, 0, 0, 0, JST),
		Emperors: []string{"後陽成天皇"},
	},
	{
		Kanji:    "慶長",
		Hiragana: "けいちょう",
		Epoch:    time.Date(1596, 12, 16, 0, 0, 0, 0, JST),
		Emperors: []string{"後水尾天皇"},
	},
	{
		Kanji:    "元和",
		Hiragana: "げんな",
		Epoch:    time.Date(1615, 9, 5, 0, 0, 0, 0, JST),
		Emperors: []string{"後水尾天皇"},
	},
	{
		Kanji:    "寛永",
		Hiragana: "かんえい",
		Epoch:    time.Date(1624, 4, 17, 0, 0, 0, 0, JST),
		Emperors: []string{"明正天皇", "後光明天皇"},
	},
	{
		Kanji:    "正保",
		Hiragana: "しょうほう",
		Epoch:    time.Date(1645, 1, 13, 0, 0, 0, 0, JST),
		Emperors: []string{"後光明天皇"},
	},
	{
		Kanji:    "慶安",
		Hiragana: "けいあん",
		Epoch:    time.Date(1648, 4, 7, 0, 0, 0, 0, JST),
		Emperors: []string{"後光明天皇"},
	},
	{
		Kanji:    "承応",
		Hiragana: "じょうおう",
		Epoch:    time.Date(1652, 10, 20, 0, 0, 0, 0, JST),
		Emperors: []string{"後西天皇"},
	},
	{
		Kanji:    "明暦",
		Hiragana: "めいれき",
		Epoch:    time.Date(1655, 5, 18, 0, 0, 0, 0, JST),
		Emperors: []string{"後西天皇"},
	},
	{
		Kanji:    "万治",
		Hiragana: "まんじ",
		Epoch:    time.Date(1658, 8, 21, 0, 0, 0, 0, JST),
		Emperors: []string{"後西天皇"},
	},
	{
		Kanji:    "寛文",
		Hiragana: "かんぶん",
		Epoch:    time.Date(1661, 5, 23, 0, 0, 0, 0, JST),
		Emperors: []string{"霊元天皇"},
	},
	{
		Kanji:    "延宝",
		Hiragana: "えんぽう",
		Epoch:    time.Date(1673, 10, 30, 0, 0, 0, 0, JST),
		Emperors: []string{"霊元天皇"},
	},
	{
		Kanji:    "天和",
		Hiragana: "てんな",
		Epoch:    time.Date(1681, 11, 9, 0, 0, 0, 0, JST),
		Emperors: []string{"霊元天皇"},
	},
	{
		Kanji:    "貞享",
		Hiragana: "じょうきょう",
		Epoch:    time.Date(1684, 4, 5, 0, 0, 0, 0, JST),
		Emperors: []string{"東山天皇"},
	},
	{
		Kanji:    "元禄",
		Hiragana: "げんろく",
		Epoch:    time.Date(1688, 10, 23, 0, 0, 0, 0, JST),
		Emperors: []string{"東山天皇"},
	},
	{
		Kanji:    "宝永",
		Hiragana: "ほうえい",
		Epoch:    time.Date(1704, 4, 16, 0, 0, 0, 0, JST),
		Emperors: []string{"中御門天皇"},
	},
	{
		Kanji:    "正徳",
		Hiragana: "しょうとく",
		Epoch:    time.Date(1711, 6, 11, 0, 0, 0, 0, JST),
		Emperors: []string{"中御門天皇"},
	},
	{
		Kanji:    "享保",
		Hiragana: "きょうほう",
		Epoch:    time.Date(1716, 8, 9, 0, 0, 0, 0, JST),
		Emperors: []string{"桜町天皇"},
	},
	{
		Kanji:    "元文",
		Hiragana: "げんぶん",
		Epoch:    time.Date(1736, 6, 7, 0, 0, 0, 0, JST),
		Emperors: []string{"桜町天皇"},
	},
	{
		Kanji:    "寛保",
		Hiragana: "かんぽう",
		Epoch:    time.Date(1741, 4, 12, 0, 0, 0, 0, JST),
		Emperors: []string{"桜町天皇"},
	},
	{
		Kanji:    "延享",
		Hiragana: "えんきょう",
		Epoch:    time.Date(1744, 4, 3, 0, 0, 0, 0, JST),
		Emperors: []string{"桃園天皇"},
	},
	{
		Kanji:    "寛延",
		Hiragana: "かんえん",
		Epoch:    time.Date(1748, 8, 5, 0, 0, 0, 0, JST),
		Emperors: []string{"桃園天皇"},
	},
	{
		Kanji:    "宝暦",
		Hiragana: "ほうれき",
		Epoch:    time.Date(1751, 12, 14, 0, 0, 0, 0, JST),
		Emperors: []string{"後桜町天皇"},
	},
	{
		Kanji:    "明和",
		Hiragana: "めいわ",
		Epoch:    time.Date(1764, 6, 30, 0, 0, 0, 0, JST),
		Emperors: []string{"後桃園天皇"},
	},
	{
		Kanji:    "安永",
		Hiragana: "あんえい",
		Epoch:    time.Date(1772, 12, 10, 0, 0, 0, 0, JST),
		Emperors: []string{"光格天皇"},
	},
	{
		Kanji:    "天明",
		Hiragana: "てんめい",
		Epoch:    time.Date(1781, 4, 25, 0, 0, 0, 0, JST),
		Emperors: []string{"光格天皇"},
	},
	{
		Kanji:    "寛政",
		Hiragana: "かんせい",
		Epoch:    time.Date(1789, 2, 19, 0, 0, 0, 0, JST),
		Emperors: []string{"光格天皇"},
	},
	{
		Kanji:    "享和",
		Hiragana: "きょうわ",
		Epoch:    time.Date(1801, 3, 19, 0, 0, 0, 0, JST),
		Emperors: []string{"光格天皇"},
	},
	{
		Kanji:    "文化",
		Hiragana: "ぶんか",
		Epoch:    time.Date(1804, 3, 22, 0, 0, 0, 0, JST),
		Emperors: []string{"仁孝天皇"},
	},
	{
		Kanji:    "文政",
		Hiragana: "ぶんせい",
		Epoch:    time.Date(1818, 5, 26, 0, 0, 0, 0, JST),
		Emperors: []string{"仁孝天皇"},
	},
	{
		Kanji:    "天保",
		Hiragana: "てんぽう",
		Epoch:    time.Date(1831, 1, 23, 0, 0, 0, 0, JST),
		Emperors: []string{"仁孝天皇"},
	},
	{
		Kanji:    "弘化",
		Hiragana: "こうか",
		Epoch:    time.Date(1845, 1, 9, 0, 0, 0, 0, JST),
		Emperors: []string{"孝明天皇"},
	},
	{
		Kanji:    "嘉永",
		Hiragana: "かえい",
		Epoch:    time.Date(1848, 4, 1, 0, 0, 0, 0, JST),
		Emperors: []string{"孝明天皇"},
	},
	{
		Kanji:    "安政",
		Hiragana: "あんせい",
		Epoch:    time.Date(1855, 1, 15, 0, 0, 0, 0, JST),
		Emperors: []string{"孝明天皇"},
	},
	{
		Kanji:    "万延",
		Hiragana: "まんえん",
		Epoch:    time.Date(1860, 4, 8, 0, 0, 0, 0, JST),
		Emperors: []string{"孝明天皇"},
	},
	{
		Kanji:    "文久",
		Hiragana: "ぶんきゅう",
		Epoch:    time.Date(1861, 3, 29, 0, 0, 0, 0, JST),
		Emperors: []string{"孝明天皇"},
	},
	{
		Kanji:    "元治",
		Hiragana: "げんじ",
		Epoch:    time.Date(1864, 3, 27, 0, 0, 0, 0, JST),
		Emperors: []string{"孝明天皇"},
	},
	{
		Kanji:    "慶応",
		Hiragana: "けいおう",
		Epoch:    time.Date(1865, 5, 1, 0, 0, 0, 0, JST),
		Emperors: []string{"明治天皇"},
	},
	{
		Kanji:    "明治",
		Hiragana: "めいじ",
		Epoch:    time.Date(1868, 1, 25, 0, 0, 0, 0, JST),
		Emperors: []string{"明治天皇"},
	},
	{
		Kanji:    "大正",
		Hiragana: "たいしょう",
		Epoch:    time.Date(1912, 7, 30, 0, 0, 0, 0, JST),
		Emperors: []string{"大正天皇"},
	},
	{
		Kanji:    "昭和",
		Hiragana: "しょうわ",
		Epoch:    time.Date(1926, 12, 25, 0, 0, 0, 0, JST),
		Emperors: []string{"昭和天皇"},
	},
	{
		Kanji:    "平成",
		Hiragana: "へいせい",
		Epoch:    time.Date(1989, 1, 8, 0, 0, 0, 0, JST),
		Emperors: []string{"明仁"},
	},
	{
		Kanji:    "令和",
		Hiragana: "れいわ",
		Epoch:    time.Date(2019, 5, 1, 0, 0, 0, 0, JST),
		Emperors: []string{"徳仁"},
	},
}
